### ISSUE TITLE
Why was `vendor/` added?

### ISSUE THREAD

**Issue by maguro** [ReactiveX/RxGo#311] opened 2021-04-07 02:31 UTC
Just curious.  What problems did adding it solve?

**Comment by teivah** [comment] 2021-04-07 07:03
I'd say mainly:
* Perfectly reproducible builds over time (even if repos are deleted)
* No need to handle cache during CI

Other popular repos in Go do the same, for example [Kubernetes](https://github.com/kubernetes/kubernetes/tree/master/vendor).

**Comment by maguro** [comment] 2021-04-07 17:49
So the concern is that a project might get deleted?

What problems w/ caching occur during CI?  Sounds interesting.

**Comment by teivah** [comment] 2021-04-07 18:06
There's no strong requirement as the project was working already without vendoring but there are some benefits imo.

**Comment by maguro** [comment] 2021-04-07 19:53
Agreed,  I was just wondering what problems w/ caching occur during CI.

**Comment by teivah** [comment] 2021-04-11 15:20
Since I switched to GH actions, things were smoother than with Travis. So, no strong requirements but it's becoming more and more the norm. 
Let's close it then, if you're okay.

**Closed by teivah** 2021-04-11 15:20 UTC
Labels: pending reply, question
